Script started on 廿十八年三月十六日 (週五) 廿時52分54秒
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

]0;pd2vm@pd2-vbox: ~/Documents/lab1[01;32mpd2vm@pd2-vbox[00m:[01;34m~/Documents/lab1[00m$ ./[K[Kg++ -o A A.cpp
]0;pd2vm@pd2-vbox: ~/Documents/lab1[01;32mpd2vm@pd2-vbox[00m:[01;34m~/Documents/lab1[00m$ ./A
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;pd2vm@pd2-vbox: ~/Documents/lab1[01;32mpd2vm@pd2-vbox[00m:[01;34m~/Documents/lab1[00m$ exit

Script done on 廿十八年三月十六日 (週五) 廿時53分55秒
