Script started on 廿十八年三月十六日 (週五) 十九時58分二秒
To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

]0;pd2vm@pd2-vbox: ~/Documents[01;32mpd2vm@pd2-vbox[00m:[01;34m~/Documents[00m$ whoami;pwd
pd2vm
/home/pd2vm/Documents
]0;pd2vm@pd2-vbox: ~/Documents[01;32mpd2vm@pd2-vbox[00m:[01;34m~/Documents[00m$ git config -l
user.name=F64051114
user.email=f64051114@mail.ncku.edu.tw
core.editor=vim
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.editor=vim
]0;pd2vm@pd2-vbox: ~/Documents[01;32mpd2vm@pd2-vbox[00m:[01;34m~/Documents[00m$ git clone git@p d2b.imslab.org:F64051114/lab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
]0;pd2vm@pd2-vbox: ~/Documents[01;32mpd2vm@pd2-vbox[00m:[01;34m~/Documents[00m$ exit

Script done on 廿十八年三月十六日 (週五) 十九時58分54秒
